### ISSUE TITLE
improperly configured error

### ISSUE THREAD

**Issue by ehsaanQCTechnologies** [twidi/django-decorator-include#16] opened 2016-12-07 15:52 UTC
```

class DecoratedPatterns(object):
    """
    A wrapper for an urlconf that applies a decorator to all its views.
    """
    def __init__(self, urlconf_name, decorators):
        try:
            iter(decorators)
        except TypeError:
            decorators = [decorators]
        self.decorators = decorators
        if isinstance(urlconf_name, str):
            self.urlconf_module = import_module(urlconf_name)
        else:
            self.urlconf_module = urlconf_name

    def decorate_pattern(self, pattern):
        if isinstance(pattern, RegexURLResolver):
            regex = pattern.regex.pattern
            urlconf_module = pattern.urlconf_name
            default_kwargs = pattern.default_kwargs
            namespace = pattern.namespace
            app_name = pattern.app_name
            urlconf = DecoratedPatterns(urlconf_module, self.decorators)
            decorated = RegexURLResolver(
                regex, urlconf, default_kwargs,
                app_name, namespace
            )
        else:
            callback = pattern.callback
            for decorator in reversed(self.decorators):
                callback = decorator(callback)
            decorated = RegexURLPattern(
                pattern.regex.pattern,
                callback,
                pattern.default_args,
                pattern.name
            )
        return decorated

    def _get_urlpatterns(self):
        try:
            patterns = self.urlconf_module.urlpatterns
        except AttributeError:
            patterns = self.urlconf_module
        return [self.decorate_pattern(pattern) for pattern in patterns]
    urlpatterns = property(_get_urlpatterns)

    def __getattr__(self, name):
        return getattr(self.urlconf_module, name)


def decorator_include(decorators, arg, namespace=None, app_name=None):
    """
    Works like ``django.conf.urls.include`` but takes a view decorator
    or an iterable of view decorators as the first argument and applies them,
    in reverse order, to all views in the included urlconf.
    """
    if isinstance(arg, tuple):
        if namespace:
            raise ImproperlyConfigured(
                'Cannot override the namespace for a dynamic module that provides a namespace'
            )
        urlconf, app_name, namespace = arg
    else:
        urlconf = arg
    decorated_urlconf = DecoratedPatterns(urlconf, decorators)
    return (decorated_urlconf, app_name, namespace)
```
and in url

```
url(r'^client_config/',
        alchemy_util.decorator_include(
            vi_ajax_login_required,
            'client_config.urls.urls')),
```

Gives me following error

```
Improperly Configured at /client_config/
The included urlconf does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.
```

**Comment by sbrandtb** [comment] 2016-12-19 15:53
This can be solved by passing a unicode string as URL name due to a `isinstance` call with `builtin.str` and `unicode_literals from future`

**Comment by jdufresne** [comment] 2017-01-13 19:09
@ehsaanQCTechnologies  Can you check if this fixed in the latest master branch? [The `isinstance()` call now checks against `six.string_types`](https://github.com/twidi/django-decorator-include/blob/master/src/decorator_include/__init__.py#L30) instead of `str`.

**Closed** 2017-01-13 21:21 UTC

**Comment by sbrandtb** [comment] 2017-01-18 12:44
I can confirm version 1.2 fixes it in my case.
